export interface BlogPost {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  date: string;
  dateISO: string;
  readTime: string;
  content: Section[];
}

interface Section {
  type: 'p' | 'h2' | 'h3' | 'ul' | 'ol' | 'callout' | 'stat-row';
  text?: string;
  items?: string[];
  stats?: { value: string; label: string }[];
}

export const POSTS: BlogPost[] = [
  {
    slug: 'why-pi-clients-hire-the-first-firm-that-answers',
    category: 'Intake Optimization',
    title: 'Why 78% of PI Clients Hire the First Firm That Answers — And What To Do About It',
    excerpt: 'Speed-to-lead is the single most important factor in converting a PI prospect into a signed client. Here\'s the data, and here\'s how to fix your intake.',
    date: 'April 2026',
    dateISO: '2026-04-10',
    readTime: '6 min read',
    content: [
      { type: 'p', text: 'A personal injury prospect doesn\'t comparison-shop the way someone buying a car does. They\'re hurt, stressed, often scared — and they call multiple firms in rapid succession. Whoever answers first, speaks with authority, and captures their information wins the client. The data on this is unambiguous.' },
      { type: 'h2', text: 'The Research Is Clear' },
      { type: 'p', text: 'A widely cited study from the Legal Marketing Association found that 78% of clients hire the first attorney who meaningfully engages with them. "Meaningfully" is doing a lot of work in that sentence — a voicemail doesn\'t count. A hold queue that rings for 4 minutes doesn\'t count. A callback 3 hours later definitely doesn\'t count.' },
      { type: 'p', text: 'The Harvard Business Review found that companies responding to web leads within 5 minutes are 21x more likely to qualify that lead than those that wait 30 minutes. For PI firms, the stakes are higher — your competitors are running the same ads, targeting the same keywords, and fighting for the same clients. The differentiator is almost never the ad itself. It\'s what happens after the click.' },
      { type: 'stat-row', stats: [
        { value: '78%', label: 'of PI clients hire the first firm that meaningfully engages' },
        { value: '21x', label: 'more likely to qualify a lead when responding within 5 minutes' },
        { value: '<5 min', label: 'target speed-to-lead for competitive PI markets' },
      ]},
      { type: 'h2', text: 'Why Most Firms Fail at Speed-to-Lead' },
      { type: 'p', text: 'The honest answer: intake is treated as an afterthought. Firms spend $15,000–$30,000 per month on Google Ads and then route inbound calls to a paralegal who also handles case management, scheduling, and a dozen other things. When that paralegal is in court prep or on another call, the $200 click you just paid for hits voicemail.' },
      { type: 'ul', items: [
        'Single-point-of-failure intake: one person handling calls, one number, no coverage plan',
        'No after-hours response — 40%+ of PI inquiries come outside 9-5',
        'No missed-call automation — a prospect who hits voicemail is gone in 90 seconds',
        'CRM not connected to the phone system — leads fall out of the pipeline entirely',
        'No follow-up sequence — a lead that doesn\'t answer on the callback is abandoned',
      ]},
      { type: 'h2', text: 'The Intake OS: What High-Converting Firms Do Differently' },
      { type: 'p', text: 'The firms closing 70–85% of their leads aren\'t spending more on advertising. They\'ve built an intake operating system that ensures no lead is lost to speed, coverage gaps, or follow-up failure.' },
      { type: 'h3', text: '1. AI Receptionist for After-Hours and Overflow' },
      { type: 'p', text: 'A GHL-connected AI voice agent answers every call that your team can\'t — nights, weekends, high-volume windows. It greets callers by firm name, qualifies the case type, captures contact information, and books a callback or consultation. The lead lands in your CRM pipeline before your team starts their morning.' },
      { type: 'h3', text: '2. Missed-Call Text-Back — Within 60 Seconds' },
      { type: 'p', text: 'Every missed call triggers an automatic SMS within 60 seconds: "Hi, this is [Firm Name] — sorry we missed you. What\'s the best time to reach you?" That text keeps the conversation alive long enough for your intake team to follow up. Without it, the prospect has already called the next firm on their list.' },
      { type: 'h3', text: '3. Multi-Touch Follow-Up Sequences' },
      { type: 'p', text: 'A prospect who doesn\'t answer your callback isn\'t necessarily gone. A properly configured follow-up sequence — call, SMS, email, repeat over 5 days — recovers a significant percentage of prospects who went cold after the first contact attempt. Most firms give up after one or two tries.' },
      { type: 'h3', text: '4. CRM Pipeline Visibility' },
      { type: 'p', text: 'If you can\'t see your leads moving through a pipeline in real time, you have no idea where you\'re losing them. Speed-to-lead metrics, contact attempt counts, conversion rates by source — these are the numbers that tell you where to fix the system.' },
      { type: 'h2', text: 'What to Do This Week' },
      { type: 'p', text: 'You don\'t need to overhaul everything at once. Start by auditing your current intake performance:' },
      { type: 'ol', items: [
        'Call your own firm from an unknown number at 7pm on a Thursday. What happens?',
        'Pull your missed call rate for the last 30 days. Every missed call is a lost case.',
        'Check your average response time for web form leads. If it\'s over 15 minutes, you\'re leaving cases on the table.',
        'Count how many follow-up attempts your team makes on a cold lead. If it\'s less than 5, you\'re giving up too early.',
      ]},
      { type: 'callout', text: 'We offer a free intake audit for PI firms — we\'ll call your firm, submit a test lead, and show you exactly where your system is leaking. No pitch, just data.' },
      { type: 'p', text: 'The first firm to answer wins. Build the system that makes sure it\'s always you.' },
    ],
  },
  {
    slug: 'ghl-voice-agents-replacing-intake-staff-at-law-firms',
    category: 'AI Automation',
    title: 'How GHL Voice Agents Are Replacing $60K/Year Intake Staff at Law Firms',
    excerpt: 'A breakdown of how we deploy AI receptionist systems that answer, qualify, and book 24/7 — without adding headcount.',
    date: 'March 2026',
    dateISO: '2026-03-18',
    readTime: '8 min read',
    content: [
      { type: 'p', text: 'The math is straightforward. A full-time intake coordinator costs $45,000–$65,000 per year in salary alone — add benefits, payroll taxes, and management overhead and you\'re at $75,000–$90,000. That person works 40 hours a week, takes sick days, goes on vacation, and can\'t handle two calls at once. An AI voice agent costs a fraction of that, works 24/7, handles unlimited simultaneous calls, and never has a bad day.' },
      { type: 'p', text: 'This isn\'t a distant future. We\'ve been deploying GHL-connected voice agents at PI and immigration law firms since late 2024, and the results consistently outperform human-only intake for after-hours and overflow coverage.' },
      { type: 'h2', text: 'What a GHL Voice Agent Actually Does' },
      { type: 'p', text: 'The term "AI receptionist" gets used loosely, so let\'s be specific. A properly configured GoHighLevel voice agent, integrated with a custom AI backend, can:' },
      { type: 'ul', items: [
        'Answer inbound calls in under 2 seconds, with a custom greeting matching your firm brand',
        'Conduct a natural-language intake interview — case type, date of injury, insurance status, contact info',
        'Qualify or disqualify leads based on your specific criteria (statute of limitations, case minimums, etc.)',
        'Book a consultation directly into your attorney\'s calendar via GHL calendar sync',
        'Trigger a CRM pipeline entry with all captured data and call recording',
        'Send a confirmation SMS to the prospect with appointment details',
        'Escalate to a live person if the caller specifically requests it or the situation warrants',
      ]},
      { type: 'h2', text: 'When to Use It — and When Not To' },
      { type: 'p', text: 'AI voice agents excel at specific, high-volume scenarios. They are not a full replacement for your intake team in all situations — and being clear about this matters for setting the right expectations.' },
      { type: 'h3', text: 'Best fit: after-hours and weekend coverage' },
      { type: 'p', text: 'Between 40–60% of inbound PI calls come outside business hours. That\'s the lowest-hanging fruit. Deploying an AI agent for nights and weekends alone — while keeping your human team for business hours — eliminates the single biggest source of lead leakage at most firms.' },
      { type: 'h3', text: 'Best fit: overflow and high-volume windows' },
      { type: 'p', text: 'A TV ad or viral social post sends 50 calls in 2 hours. Your intake coordinator can handle 2–3. The rest hit voicemail. An AI agent handles the overflow queue in real time, ensuring every caller gets a response within seconds.' },
      { type: 'h3', text: 'Use with caution: high-emotion, complex intake' },
      { type: 'p', text: 'A caller who just came from the ER describing a serious injury needs empathy that current AI handles imperfectly. Our configuration routes these calls to a human escalation queue automatically based on case type and emotional tone detection. The AI captures initial info and the human closes the intake.' },
      { type: 'stat-row', stats: [
        { value: '24/7', label: 'coverage with no additional headcount' },
        { value: '<2s', label: 'average answer time vs. 4+ rings for human agents' },
        { value: '~70%', label: 'of after-hours leads handled to completion by AI' },
      ]},
      { type: 'h2', text: 'The Technical Stack We Use' },
      { type: 'p', text: 'Our voice agent deployments are built on GoHighLevel as the CRM and automation backbone, with a custom AI conversation layer connected via the GHL API. The key components:' },
      { type: 'ul', items: [
        'GHL phone number with call routing rules (business hours → human team, after-hours → AI agent)',
        'Custom AI model fine-tuned on intake qualification scripts for PI, immigration, or the relevant practice area',
        'Twilio integration for call recording and SMS confirmations',
        'GHL pipeline automation triggered on call completion — contact created, lead stage set, follow-up sequence enrolled',
        'Intake dashboard showing call volume, qualification rate, booking rate by source',
      ]},
      { type: 'h2', text: 'What Firms Are Saving' },
      { type: 'p', text: 'A realistic breakdown for a firm handling 300 inbound leads per month with a human-only intake team:' },
      { type: 'ul', items: [
        'Cost of missed after-hours leads (assuming $3,000 case value, 40% after-hours, 20% close rate): ~$72,000/year in lost revenue',
        'Cost of a second intake coordinator to cover after-hours: $75,000–$90,000/year',
        'Cost of AI voice agent deployment and GHL configuration: significantly less than either of the above',
      ]},
      { type: 'p', text: 'We won\'t publish specific pricing here because it varies by call volume and complexity of the intake script. But the ROI case is rarely close — it\'s usually obvious within the first 90 days.' },
      { type: 'callout', text: 'Curious what this would look like for your firm? We\'ll run a free intake audit and show you exactly how many after-hours leads you\'re currently missing — and what an AI agent would have captured.' },
    ],
  },
  {
    slug: 'patient-recall-system-reactivated-lapsed-patients',
    category: 'Medical Marketing',
    title: 'The Patient Recall System That Reactivated 60% of Lapsed Patients for a Florida Dental Practice',
    excerpt: 'Your existing patient database is worth more than any ad campaign. Here\'s the exact automation sequence we used.',
    date: 'March 2026',
    dateISO: '2026-03-05',
    readTime: '5 min read',
    content: [
      { type: 'p', text: 'Most medical and dental practices are sitting on a gold mine they\'ve never touched: their existing patient database. Patients who came in once or twice, had a good experience, and then simply… drifted. Life happened. They got busy. They forgot to book a follow-up. They\'re not unhappy with your practice — they just need a reason to come back.' },
      { type: 'p', text: 'A patient recall system gives them that reason. Done right, it\'s the highest-ROI marketing activity available to most practices — because you\'re marketing to people who already trust you.' },
      { type: 'h2', text: 'The Problem We Were Solving' },
      { type: 'p', text: 'A general dentistry practice in South Florida came to us with a specific problem: they had 2,400 patients in their system who hadn\'t been in for over 18 months. Their front desk was making recall calls — slowly, inconsistently, about 15–20 per week when time allowed. At that rate, it would take 2–3 years to work through the list once, by which point the oldest contacts would be 5 years cold.' },
      { type: 'p', text: 'They were also spending $4,500/month on Google Ads to attract new patients while leaving thousands of warm relationships untouched.' },
      { type: 'h2', text: 'The Recall Sequence We Built' },
      { type: 'p', text: 'We built a 5-touch automated sequence in GoHighLevel, triggered for any patient who hit the 18-month mark without a completed appointment. The sequence ran over 30 days:' },
      { type: 'ol', items: [
        'Day 1 — SMS: Personalized, casual, low-pressure. "Hi [Name], it\'s [Practice Name] — it\'s been a while and we wanted to check in. We have some openings this week if you\'ve been meaning to come in. Reply BOOK and we\'ll send a link."',
        'Day 3 — Email: Slightly more detailed. Highlights any new services, mentions the hygienist by name if they had a consistent provider, includes direct booking link.',
        'Day 7 — SMS #2: Simple follow-up if no response. "Still have a few spots open this month — would love to see you back. Book here: [link]"',
        'Day 14 — Email #2: "We haven\'t heard from you — no worries at all. Just wanted to make sure you have our info if you need us." Includes phone number and booking link.',
        'Day 30 — Final SMS: "Last note from us for a while — if you\'ve found a new provider we completely understand. If not, we\'d love to have you back." Then removed from the sequence.',
      ]},
      { type: 'h2', text: 'The Results After 90 Days' },
      { type: 'stat-row', stats: [
        { value: '60%', label: 'of contacted patients booked an appointment within 30 days' },
        { value: '412', label: 'reactivated appointments from 2,400 lapsed patients' },
        { value: '$0', label: 'in ad spend — reactivation is pure margin improvement' },
      ]},
      { type: 'p', text: 'At an average appointment value of $280, those 412 reactivated appointments represented roughly $115,000 in recovered revenue — against a setup cost that was a fraction of that. The practice has since reduced their Google Ads spend by $1,500/month and redirected it to a new patient acquisition campaign, since they no longer need ads to compensate for lapsed-patient attrition.' },
      { type: 'h2', text: 'What Made It Work' },
      { type: 'ul', items: [
        'Personalization: messages referenced the patient\'s name, previous provider, and last visit context where available',
        'Low pressure tone: no urgency manufacturing, no "limited time offer" — just a genuine check-in',
        'Direct booking link: every touchpoint made it frictionless to respond. No phone tag required.',
        'Correct timing: 18 months is the sweet spot for dental. Shorter sequences work better for higher-frequency practices (chiro, physio). Longer for lower-frequency (specialty medical).',
        'Suppression list: patients with open billing disputes or who had explicitly left the practice were excluded from the sequence automatically',
      ]},
      { type: 'h2', text: 'How to Set This Up for Your Practice' },
      { type: 'p', text: 'The core components you need: a CRM with automation capability (GHL is what we use, but HubSpot or even a capable EHR works), a texting-enabled phone number, and a clean patient list with last-visit dates and contact info.' },
      { type: 'p', text: 'The sequence itself is straightforward to build once you have those pieces in place. The harder part is segmenting correctly — patients who are 18 months lapsed need a different message than patients who are 6 months lapsed, and patients who had a bad experience (even if they never said so) need to be identified and handled differently.' },
      { type: 'callout', text: 'We build and configure patient recall systems for medical and dental practices. If you\'d like to know how many lapsed patients are in your database and what they\'re worth, we\'ll run the analysis for free.' },
    ],
  },
  {
    slug: 'the-5-minute-rule-response-time-case-acquisition',
    category: 'Intake Optimization',
    title: 'The 5-Minute Rule: How Response Time Affects Your Case Acquisition Rate',
    excerpt: 'After analyzing intake data across 30+ PI firms, the pattern is clear: firms that respond in under 5 minutes close at 3x the rate of those that don\'t.',
    date: 'February 2026',
    dateISO: '2026-02-08',
    readTime: '5 min read',
    content: [
      { type: 'p', text: 'There\'s a number every personal injury attorney should have memorized: 5 minutes. That\'s the response time threshold that separates firms that close cases from firms that generate expensive clicks for their competitors.' },
      { type: 'p', text: 'After working with intake systems across more than 30 PI firms, reviewing thousands of lead records, and testing response time interventions in controlled conditions, the pattern is consistent enough to call it a rule.' },
      { type: 'h2', text: 'The Data' },
      { type: 'stat-row', stats: [
        { value: '3x', label: 'close rate for firms responding within 5 minutes vs. 30+ minutes' },
        { value: '62%', label: 'of PI prospects contact 3+ firms before choosing one' },
        { value: '11 min', label: 'average response time for PI firm web leads — too slow' },
      ]},
      { type: 'p', text: 'The 3x figure is the headline, but the mechanism matters more than the number. A PI prospect who submits a web form or calls and hits voicemail is not waiting for you. They\'re submitting to the next firm on their search results page. By the time you call back 45 minutes later, they\'ve already spoken with 2–3 competitors and may have a consultation booked.' },
      { type: 'h2', text: 'Why the First 5 Minutes Are Different' },
      { type: 'p', text: 'The first 5 minutes after a lead inquiry is a unique psychological window. The prospect is in active decision mode — they\'ve just searched, found your firm, and taken action. Their intent is at its peak. When you respond immediately, you\'re the answer to an active search. When you respond later, you\'re an interruption.' },
      { type: 'p', text: 'Beyond psychology, there\'s a simple competitive reality: the first firm to get the prospect on the phone gets to set the frame. You get to ask the questions, build rapport, assess the case, and — critically — you get to tell them why you\'re the right firm before they\'ve talked to anyone else.' },
      { type: 'h2', text: 'Where Response Time Breaks Down' },
      { type: 'p', text: 'We\'ve audited intake systems at dozens of firms. The same failure points appear consistently:' },
      { type: 'ul', items: [
        'Web form leads not routed to mobile — intake staff only see them when they\'re at their desk',
        'Calls going to voicemail during lunch, meetings, or when the intake person is on another call',
        'After-hours leads sitting in an email inbox until the next morning',
        'CRM not configured to alert anyone when a new lead comes in',
        'Intake calls handled by attorneys who are in depositions or court the majority of the day',
      ]},
      { type: 'h2', text: 'How to Fix It' },
      { type: 'p', text: 'The goal is a guaranteed sub-5-minute response for every inbound inquiry, 24 hours a day. That sounds ambitious, but it\'s achievable with the right systems:' },
      { type: 'h3', text: 'For business hours' },
      { type: 'ul', items: [
        'Dedicated intake line with a person whose primary job is answering — not case management, not scheduling, not filing',
        'Web form leads trigger an immediate SMS and email to the intake coordinator\'s phone',
        'Backup coverage plan for when the primary intake person is on a call',
      ]},
      { type: 'h3', text: 'For after-hours' },
      { type: 'ul', items: [
        'AI voice agent answers after-hours calls, conducts initial intake, and books callbacks',
        'Missed-call text-back fires within 60 seconds of any unanswered call',
        'Web form leads after hours trigger an immediate SMS to the prospect: "We received your inquiry and will call you first thing tomorrow at [time]. In the meantime, here\'s what to expect..."',
      ]},
      { type: 'h2', text: 'Measuring Your Current Performance' },
      { type: 'p', text: 'Before you can fix your response time, you need to know what it actually is — not what you think it is. Most firms significantly underestimate how long their responses take.' },
      { type: 'ol', items: [
        'Submit a test lead from a personal email address on a Friday afternoon and track when you receive a response',
        'Call your main number at 7pm and note what happens',
        'Pull your CRM data: filter leads by source and look at the timestamp delta between lead creation and first contact attempt',
        'Ask your intake coordinator: how many calls do they miss on a typical day? What happens to those leads?',
      ]},
      { type: 'callout', text: 'We\'ll run this audit for you — for free. We\'ll call your firm, submit test leads, and give you a report on your actual response times and where leads are being lost. It takes 48 hours and requires nothing from your team.' },
    ],
  },
  {
    slug: 'from-30-to-85-percent-intake-conversion-south-florida-pi-firm',
    category: 'Case Study',
    title: 'From 30% to 85% Intake Conversion: How One South Florida PI Firm Fixed Its Funnel',
    excerpt: 'A full walkthrough of the intake audit, the systems we built, and the results six months later.',
    date: 'January 2026',
    dateISO: '2026-01-15',
    readTime: '10 min read',
    content: [
      { type: 'p', text: 'This is the story of a 4-attorney personal injury firm in South Florida — we\'re keeping their name anonymous at their request — that went from closing roughly 30% of their inbound leads to closing 85% in approximately 90 days. The change wasn\'t in their advertising, their case quality, or their attorneys. It was entirely in their intake system.' },
      { type: 'h2', text: 'The Starting Point' },
      { type: 'p', text: 'The firm came to us in mid-2025 with a specific complaint: they were spending $18,000/month on Google Ads and their PPC agency kept showing them impressive click metrics, but signed case volume felt flat. Their managing partner had done the math: at $18,000/month, they needed to be closing at least 6–8 cases per month from PPC to justify the spend. They were closing 2–3.' },
      { type: 'p', text: 'The instinct was to blame the ads. "We\'re probably targeting the wrong keywords" was the working hypothesis. We had a different suspicion.' },
      { type: 'h2', text: 'The Audit' },
      { type: 'p', text: 'Before recommending any changes, we conducted a 2-week intake audit. The methodology:' },
      { type: 'ul', items: [
        'Submitted 15 test leads through their website contact form at various times of day and week',
        'Called their main number 20 times across business hours, after-hours, and lunch',
        'Reviewed 3 months of CRM data (they were using a basic spreadsheet, not a proper CRM)',
        'Interviewed their intake coordinator and two of the attorneys',
        'Reviewed call recordings from their phone system',
      ]},
      { type: 'p', text: 'What we found was not a keyword problem.' },
      { type: 'h2', text: 'What We Found' },
      { type: 'stat-row', stats: [
        { value: '40%', label: 'of test calls went to voicemail during business hours' },
        { value: '6.2 hrs', label: 'average response time for web form leads' },
        { value: '0', label: 'after-hours coverage — all calls went to a voicemail box that wasn\'t checked until the next day' },
      ]},
      { type: 'p', text: 'The single intake coordinator — a paralegal who also handled case file management — was handling roughly 25–30 inbound inquiries per week. But she was also managing 3 active case files, handling court filings, and coordinating with medical providers. Intake wasn\'t her job; it was an additional responsibility.' },
      { type: 'p', text: 'Of the test leads submitted after 5pm or on weekends — which represented roughly 38% of their actual lead volume based on CRM timestamps — exactly zero received any response before the next business day. By that point, our test "prospects" had long since moved on.' },
      { type: 'h2', text: 'The Build: What We Implemented' },
      { type: 'h3', text: 'Phase 1: CRM and Pipeline (Week 1–2)' },
      { type: 'p', text: 'We migrated them from a spreadsheet to GoHighLevel, configured a 5-stage intake pipeline (New Lead → Contacted → Consultation Booked → Case Screened → Signed), and set up real-time notifications so every new lead triggered an immediate SMS alert to the coordinator\'s phone.' },
      { type: 'h3', text: 'Phase 2: AI Voice Agent for After-Hours (Week 2–3)' },
      { type: 'p', text: 'We deployed a GHL-connected AI voice agent on a dedicated after-hours line. Calls to the main number after 5:30pm and on weekends route to the AI agent, which:' },
      { type: 'ul', items: [
        'Greets callers with the firm\'s name and a warm introduction',
        'Asks about the incident, injury type, and when it occurred',
        'Collects contact information and best callback time',
        'Explains what to expect next and books a callback for the next morning',
        'Creates a GHL contact record with all captured information and flags it as after-hours',
      ]},
      { type: 'h3', text: 'Phase 3: Missed-Call Text-Back and Follow-Up Sequence (Week 3–4)' },
      { type: 'p', text: 'Any missed call during business hours now triggers an automatic SMS within 90 seconds: a brief, personal message from the firm with a direct callback number. Web form leads trigger an immediate auto-response SMS with a message acknowledging the inquiry and setting timeline expectations.' },
      { type: 'p', text: 'Leads that don\'t respond to the initial contact attempt enter a 5-day follow-up sequence: 2 additional call attempts, 2 SMS touches, and an email. After 5 days with no response, the lead is marked cold and removed from active follow-up.' },
      { type: 'h3', text: 'Phase 4: Intake Training and Process (Week 4)' },
      { type: 'p', text: 'We worked with the coordinator on a structured intake script and qualification checklist, reducing each intake call from an average of 22 minutes to 12 minutes without reducing the quality of information captured. This freed up enough time for her to handle the increased lead volume without additional headcount.' },
      { type: 'h2', text: 'The Results: 90 Days Later' },
      { type: 'stat-row', stats: [
        { value: '85%', label: 'intake conversion rate (up from 30%)' },
        { value: '<90s', label: 'average speed-to-lead' },
        { value: '+42%', label: 'signed cases in 90 days' },
      ]},
      { type: 'p', text: 'The PPC budget stayed the same. The ad creative didn\'t change. The keyword strategy didn\'t change. What changed was that for the first time, most of the leads their ads generated actually made it through the intake funnel.' },
      { type: 'p', text: 'Their cost per signed case dropped from approximately $9,000 to $5,200 — not because ads got cheaper, but because they stopped wasting the leads they were already generating.' },
      { type: 'h2', text: 'What This Means for Your Firm' },
      { type: 'p', text: 'If you\'re running paid search and your intake system relies on a single person answering calls during business hours, there\'s a high probability you\'re in the same situation this firm was in. The number of cases you\'re closing is probably significantly lower than the number of cases you\'re generating.' },
      { type: 'p', text: 'The fix isn\'t more ad spend. It\'s building an intake system that converts the leads you\'re already paying for.' },
      { type: 'callout', text: 'We offer a free intake audit — the same 2-week process we ran for this firm. We\'ll test your system, show you your real response times and conversion rate, and give you a specific action plan. No obligation.' },
    ],
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  'Intake Optimization': 'bg-blue-50 text-blue-700',
  'AI Automation': 'bg-purple-50 text-purple-700',
  'Medical Marketing': 'bg-green-50 text-green-700',
  'Performance Marketing': 'bg-orange-50 text-orange-700',
  'Case Study': 'bg-red-50 text-red-700',
};
